spring:
  datasource:
    url: jdbc:h2:mem:product_db;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true